import logging
import functools

from helpers import dependency
from skeletons.gui.game_control import IBattleRoyaleTournamentController
import BigWorld
from battle_royale.BattleRoyaleTournament import CMD_BATTLE_ROYALE_TRN_JOIN, CMD_BATTLE_ROYALE_TRN_LEAVE, CMD_BATTLE_ROYALE_TRN_READY

