# Python bytecode 2.7 (decompiled from Python 2.7)
# Embedded file name: scripts/client/AimTrigger.py

import BigWorld
import TriggersManager

# AimTrigger class inherits from BigWorld.UserDataObject and is used to create a trigger for aiming
class AimTrigger(BigWorld.UserDataObject):

    def __init__(self):
        # Call the constructor of the parent class
        BigWorld.UserDataObject.__init__(self)
        
        # Initialize the unique id for the trigger
        # The id is generated by TriggersManager and is used to identify the trigger
        self.__id = TriggersManager.g_manager.addTrigger(TriggersManager.TRIGGER_TYPE.AIM, name=self.name, position=self.position, radius=self.radius, maxDistance=self.maxDistance)

    def destroy(self):
        # Remove the trigger with the id stored in self.__id
        TriggersManager.g_manager.delTrigger(self.__id)

